name: Django CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install -r requirements.txt
        pip install Django
        pip install pymysql
        pip install django-debug-toolbar
    - name: Run Tests
      run: |
        python project/manage.py test

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: lyserver_web

    steps:
    - uses: actions/checkout@v4
    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.WEB_SSH_KEY }}
    - name: Add SSH known hosts
      run: |
        ssh-keyscan -H 172.28.226.114 >> ~/.ssh/known_hosts
    - name: Deploy to server
      run: |
        # 连接到服务器并执行部署命令
        ssh web@172.28.226.114 "cd /data/web/CottonOGD/OGD && \
        git pull origin master && \
        screen -d OGD && \
        screen -r OGD && \
        cd /data/web/CottonOGD/OGD && \
        pip install -r requirements.txt && \
        source virtual/bin/activate && \
        pip install -r requirements.txt && \
        python project/manage.py migrate && \
        python project/manage.py collectstatic --noinput "



